### ISSUE TITLE
Demonstrate how Smart Study solves industry problem

### ISSUE THREAD

**Issue by jrd623** [openstax/2019-interns-team3#11]
As per the Final Presentation Rubric: "Product is convincingly presented as a solution to fill this void," void being the industry opportunity.

**Comment by AliciaZong** [comment]
https://docs.google.com/presentation/d/1KOj_f2sNZLzUzLzm6AGTF4HUqTvm-cEuEDuLHExlnkc/edit?usp=sharing

<blockquote><div><strong><a href="https://docs.google.com/presentation/d/1KOj_f2sNZLzUzLzm6AGTF4HUqTvm-cEuEDuLHExlnkc/edit?usp=sharing">Google Slides - create and edit presentations online, for free.</a></strong></div><div>Create a new presentation and edit with others at the same time. Get stuff done with or without an internet connection. Use Slides to edit PowerPoint files. Free from Google.</div></blockquote>
