### ISSUE TITLE
Talk to Phil G. about spaced repetition/highlighting research

### ISSUE THREAD

**Issue by jrd623** [openstax/2019-interns-team3#5]
# Description
Describe the desired change.

# Acceptance Criteria
Give criteria for acceptance.

**Comment by rosemaryyang** [comment]
https://docs.google.com/document/d/18ocaZSapG6ThnjBIyicPKc5MsbSIfLV5JCAt9iv5A2o/edit#

<blockquote><div><strong><a href="https://docs.google.com/document/d/18ocaZSapG6ThnjBIyicPKc5MsbSIfLV5JCAt9iv5A2o/edit#">Google Docs - create and edit documents online, for free.</a></strong></div><div>Create a new document and edit with others at the same time -- from your computer, phone or tablet. Get stuff done with or without an internet connection. Use Docs to edit Word files. Free from Google.</div></blockquote>
